Restaurant/Restaurant.WebApp/Models/ErrorViewModel.cs
using System;

namespace Restaurant.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Restaurant/Restaurant.WebApp/Models/Restaurant.cs
using Restaurant.Models;
using System.Collections.Generic;

namespace Restaurant.WebApp.Models
{
    public class Restaurant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public double Rating { get; set; }
        public string Type { get; set; }
        public virtual ICollection<Menu> Menus { get; set; } = new List<Menu>();
        public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
    }
}

Restaurant/Restaurant.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Restaurant.ViewModel;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Restaurant.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Restaurant/Restaurant.WebApp/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Restaurant.WebApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class RestaurantController : ControllerBase
    {
    }
}

Restaurant/Restaurant.WebApp/Controllers/RestaurantsController.cs
namespace Restaurant.WebApp.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Restaurant.Services;
    using Restaurant.ViewModel.Restaurants;
    using System.Collections.Generic;
    public class RestaurantsController : Controller
    {
        private readonly RestaurantsService restaurantsService;

        public RestaurantsController()
        {
            this.restaurantsService = new RestaurantsService();
        }
        public IActionResult Index(int page = 1)
        {
            RestaurantsIndexViewModel models = new RestaurantsIndexViewModel();
            models.PageNumber = page;
            models = restaurantsService.GetRestaurants(models);
            return View(models);
        }
        public IActionResult LowestRated()
        {
            List<RestaurantIndexViewModel> model = restaurantsService.GetLowestRatedRestaurants();
            return View(model);
        }

        public IActionResult HighestRated()
        {
            List<RestaurantIndexViewModel> model = restaurantsService.GetHighestRatedRestaurants();
            return View(model);
        }
    }
}

Restaurant/Restaurant.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <section id="header" style="padding:120px 0 120px 0">
        <h1 class="display-4" id="h1" text>Welcome to DiKy</h1>
    </section>



</div>
<style>
    #header {
        background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.6)), url('https://scontent-sof1-1.xx.fbcdn.net/v/t39.30808-6/337534141_594260929304729_5615431168623235943_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=730e14&_nc_ohc=qhIonzDmlekAX-oZExD&_nc_ht=scontent-sof1-1.xx&oh=00_AfBpOm96MYudwDaRx1m0avlrYcYYC58vAMCck2D43JcRsA&oe=641E73CB') no-repeat;
        background-size: cover;
    }

    #h1 {
        padding: 150px 0 150px 0;
        color: white;
        font-weight: 800;
    }
</style>

Restaurant/Restaurant.WebApp/Views/Restaurants/HighestRated.cshtml
@model List<Restaurant.ViewModel.Restaurants.RestaurantIndexViewModel>


<div class="jumbotron">
    <h2 class="display-4">Highest rated restaurants</h2>
    <hr />
    <div class="container">
        <div class="row mx-auto ">
            @foreach (var item in Model)
            {
                    <div class="card mx-auto my-1" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">@item.Name</h5>
                            <p class="card-text">Location: @item.Location</p>
                            <p class="card-text">Type: @item.Type</p>
                            <p class="card-text">Rating: @item.Rating</p>
                            <img class="img-thumbnail" src="@item.ImageUrl" />
                        @*<a href="#" class="btn btn-primary">Go somewhere</a>*@
                        </div>
                    </div>
            }
        </div>
    </div>
</div>

Restaurant/Restaurant.WebApp/Views/Restaurants/Index.cshtml
@model Restaurant.ViewModel.Restaurants.RestaurantsIndexViewModel

<h1>Restaurants page</h1>


<table class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Location</th>
            <th>Rating</th>
            <th>Image</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var p in Model.Restaurants)
        {
            <tr>
                <td>@p.Name</td>
                <td>@p.Type</td>
                <td>@p.Location</td>
                <td>@p.Rating</td>
                <td><img src="@p.ImageUrl" width="300px" height="150px" /></td>
            </tr>
        }
    </tbody>
    <tfoot>
    </tfoot>
</table>
<partial name="_PagingPartial"/>

Restaurant/Restaurant.WebApp/Views/Restaurants/LowestRated.cshtml
@model List<Restaurant.ViewModel.Restaurants.RestaurantIndexViewModel>


<div class="jumbotron">
    <h2 class="display-4">Lowest rated restaurants</h2>
    <hr />
    <div class="container">
        <div class="row mx-auto ">
            @foreach (var item in Model)
            {
                <div class="card mx-auto my-1" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">@item.Name</h5>
                        <p class="card-text">Location: @item.Location</p>
                        <p class="card-text">Type: @item.Type</p>
                        <p class="card-text">Rating: @item.Rating</p>
                        <img class="img-thumbnail" src="@item.ImageUrl" />
                        @*<a href="#" class="btn btn-primary">Go somewhere</a>*@
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Restaurant/Restaurant.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restaurant.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Restaurant.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="Index">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="LowestRated">Lowest rated</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="HighestRated">Highest rated</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Restaurant.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Restaurant/Restaurant.WebApp/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel
<nav aria-label="..." class="">
    <ul class="pagination  justify-content-center ">
        <li class="page-item @if (!Model.HasPreviousPage) {
        <text>disabled</text>
 }">
            <a class="page-link" asp-action="@Model.Action" asp-route-page="@Model.PreviousPageNumber">
                <i class="fas fa-step-backward"></i>
                Previos
            </a>
        </li>
        @for (int i = Model.PageNumber - 2; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-route-page="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 2; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-route-page="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) {
        <text>disabled</text>
 }">
            <a class="page-link" asp-action="@Model.Action" asp-route-page="@Model.NextPageNumber"><i class="fas fa-step-forward"></i>Next</a>
        </li>
    </ul>
</nav>


@*<partial name="_PagingPartial" />*@